config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  root 'welcome#index'

  get 'about' => 'welcome#about'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    if params[:country] == nil
      @destinations = Destination.all 
    else
      if params[:country] == "USA"
        @destinations = Destination.where(country: "USA")
      else
      @destinations = Destination.where(country: params[:country].titleize)
    end
  end

    @my_countries = Destination.select(:country).order(:country).distinct

  end


  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :description, :population)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@homeland = 'India'

  	@countries = ["Brazil", "China", "Japan"]

  	@travel_pics = {"Brazil" => "brazil.jpg", "Great Wall" => "great_wall.jpg", "Mt fuji" => "mt_fuji.jpg", "Rio de Janeiro" => "rio_de_Janeiro.jpg"}
  end

  def about
  	@color = params[:color]
  	@size = params[:size].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :country %><br>
    <%= f.text_field :country, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :population %><br>
    <%= f.number_field :population, class: "form-control" %>
  </div>
  <div class="actions form-group">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

  

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Destinations</h1>

  <%= link_to 'New Destination', new_destination_path, class: "btn btn-info" %>

<ul class="nav nav-pills" role="tablist">
  <li>
    <%= link_to "All Destinations", destinations_path %>
  </li>
    <% @my_countries.each do |c| %>
  <li>
    <%= link_to c.country, destinations_path(country: c.country) %>
  </li>
  <% end %>
</ul>

<div class="row">
    <% @destinations.each do |destination| %>
      <div class="col-md-4">
       <div class="well">
         <p><%= "#{destination.city}, #{destination.country}" %></p>
         <p><%= destination.description %></p>
         <p>
            <%= link_to 'Show', destination, class: "btn btn-primary" %>
            <%= link_to 'Edit', edit_destination_path(destination), class: "btn btn-info" %>
            <%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-success" %>
         </p>
       </div>
      </div>
  <% end %>
</div>

<br>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<div class="show-page">
<h1><%= "#{@destination.city}, #{@destination.country}" %></h1>
	<p>Population <%= number_with_delimiter @destination.population %></p>

<p>
  <%= @destination.description %>
</p>

<div class="btn-group">
  <%= link_to 'Edit', edit_destination_path(@destination), class: "btn btn-info" %> 
  <%= link_to 'Back', destinations_path, class: "btn btn-primary" %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travel</title>
<!-- Latest compiled and minified CSS -->
<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css", integrity: "sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7", crossorigin: "anonymous"%>

<!-- Latest compiled and minified JavaScript -->
 <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js", integrity: "sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS", crossorigin: "anonymous" %>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Destinations", destinations_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path(color: "yellow", size: 12) %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/welcome/about.html.erb
<style>

  body {
    background: <%= @color %>;
  }
</style>



<h1>About Me</h1>
<p>Lots of interesting stuffs.</p>
<p>My favorite color is <%= @color %></p>
<p>My shoes size is <%= @size %></p>

<% if @size > 12 %>
  <p>I have HUGE feet.</p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to the Travel Site</h1>
<p>A cool travel site.</p>

<p>
	<%= @homeland %>
</p>

<ul>
  <% @countries.each do |country| %>
  <li><%= country %></li>
  <% end %>
</ul>

<p>
	<% @travel_pics.each do |alt, pic| %>
		<%= image_tag pic, alt: alt, width: "250" %>
	<% end %>
</p>